; HELPID.INC--
; Copyright (C) 2017 Asmc Developers
ifndef __HELPID_INC
define __HELPID_INC

HELPID_02	equ 0643h	; <> Compressed File Support
HELPID_03	equ 07C6h	; <> Viewer Support
HELPID_04	equ 0A12h	; <> Editor Support
HELPID_05	equ 0B61h	; <> Internal Editor
HELPID_06	equ 1AE5h	; <> Extension and Filename Support
HELPID_07	equ 1ECDh	; <> Doszip Commander Environment Variables
HELPID_08	equ 2521h	; <> Installing Commander under Windows
HELPID_09	equ 2664h	; <> Creating a tools menu
HELPID_10	equ 2BB8h	; <> The File Search utility
HELPID_11	equ 322Ch	; <> Create List File
HELPID_12	equ 3553h	; <> Operation Filter
HELPID_13	equ 37CEh	; <> Shortcut keys
HELPID_14	equ 2EA3h	; <> Compare Directories
HELPID_15	equ 4610h	; <> Configuration Defaults
HELPID_16	equ 1891h	; <> Hex Editor

view_readme	proto :dword

endif
