.xlist
HELPID_01 equ 04CEh	; <> Memory Requirements
HELPID_02 equ 0963h	; <> Compressed File Support
HELPID_03 equ 0AE2h	; <> Viewer Support
HELPID_04 equ 0CB8h	; <> Editor Support
HELPID_05 equ 0E05h	; <> Internal Editor
HELPID_06 equ 19FEh	; <> Extension and Filename Support
HELPID_07 equ 1DDEh	; <> Doszip Commander Environment Variables
HELPID_08 equ 2329h	; <> Installing Commander under Windows
HELPID_09 equ 246Ch	; <> Creating a tools menu
HELPID_10 equ 29C3h	; <> The File Search utility
HELPID_11 equ 2F98h	; <> Create List File
HELPID_12 equ 319Fh	; <> Operation Filter
HELPID_13 equ 341Ah	; <> Shortcut keys
HELPID_14 equ 2CACh	; <> Compare Directories
.list
